### ISSUE TITLE
Error on configure save and fetch

### ISSUE THREAD

**Issue by ChawiBiker** [micahflee/semiphemeral#103]
I receive two errors.
First when I save in the browser

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

This happens only when I have all 4 keys entered and my twitter name. Else it saves normally if for example one is missing.

Second error is when I perform semiphemeral fetch

> semiphemeral 0.7
> Traceback (most recent call last):
>   File "/usr/local/bin/semiphemeral", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
>     return __callback(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/semiphemeral/__init__.py", line 61, in fetch
>     t = Twitter(common)
>   File "/usr/local/lib/python3.9/site-packages/semiphemeral/twitter.py", line 33, in __init__
>     self.api = tweepy.API(
> TypeError: __init__() got an unexpected keyword argument 'wait_on_rate_limit_notify'

I managed to upgrade my dev account meaning I use Twitter API v1.1
Tweepy is running on version 3.10.0
I'm running this on OS X 11.6.4

> Name: tweepy
> Version: 3.10.0
> Summary: Twitter library for Python
> Home-page: https://www.tweepy.org/
> Author: Joshua Roesslein
> Author-email: tweepy@googlegroups.com
> License: MIT
> Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
> Requires: requests, requests-oauthlib, six
> Required-by: 

Any idea what is going wrong and what I could do in order to fix this?

**Comment by byteborg** [comment]
Same here, RasPi on bullseye, Python 3.9.2/Pip 20.3.4, semiphemeral==0.7

**Comment by byteborg** [comment]
Ah, I've just seen #92 - old tweepy version being the culprit here...

**Comment by th3joker3000** [comment]
I've installed the latest tweepy version (3.9.0) but it doesn't work either.
I also installed the version 3.7.0 but it still fails to work.

**Comment by KopfKrieg** [comment]
Had the same problem, but works for me if I install `tweepy<4.0`

**Comment by deybhayden** [comment]
As long as your account applies for Elevated Access (done from the [project dashboard](https://developer.twitter.com/en/portal) and is approved, this tool works as intended (using v1.1 APIs)

**Comment by ChawiBiker** [comment]
I managed to run it now with binding to tweeps 3.7.0 on install. Sadly despite v1.1 api I only get 3000 tweets :(

**Comment by JohnVeness** [comment]
@ChawiBiker If you clone the master branch you can use the "import" feature added in #23 to populate the database. That should get all your tweets.

**Comment by ChawiBiker** [comment]
@JohnVeness thank you. I will try to understand how this works :)

**Comment by davegallant** [comment]
> Had the same problem, but works for me if I install `tweepy<4.0`

This fixed it for me. The tweepy version should probably be constrained in [setup.py](https://github.com/micahflee/semiphemeral/blob/e4845b518bbe7b48c844650004236123c2b1fb5e/setup.py#L34) or the function call fixed for the new api.

**Comment by pdelteil** [comment]
> Had the same problem, but works for me if I install `tweepy<4.0`

To save people some time, just run: 

``pip install tweepy==3.10.0`` 

Then, run `semipheral configure` and then `semipheral fetch`

**Comment by umrath** [comment]
> > Had the same problem, but works for me if I install `tweepy<4.0`
> 
> To save people some time, just run:
> 
> `pip install tweepy==3.10.0`
> 
> Then, run `semipheral configure` and then `semipheral fetch`

sadly, even then it fails for me (macos).

**Comment by byteborg** [comment]
`pip install -U tweepy==3.10.0` when another version was installed previously.
You will need to have a pretty old developer account for it functioning without paying, though. 
v1 API access seems to be a $$$ feature now.

**Comment by graciano** [comment]
Hey @byteborg, what do you mean by this?

> You will need to have a pretty old developer account for it functioning without paying, though.
v1 API access seems to be a $$$ feature now.

It's a paid feature on twitter? So in the case of someone who just created the credentials there, either update the code to work with the new version or pay twitter. Am I interpreting this correctly?

**Comment by byteborg** [comment]
> It's a paid feature on twitter? So in the case of someone who just created the credentials there, either update the code to work with the new version or pay twitter. Am I interpreting this correctly?

That's how I understood the Twitter API documentation at the time. YMMV, they are changing a lot these days...
