### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by JohnVeness** [micahflee/semiphemeral#104]
The README doesn't mention the "import" feature added in #23, and still says that deleting more than 3000 tweets might not work (which I hope is no longer the case).

EDIT: I've just noticed that "import" isn't in a released (tagged) version, so maybe it's time for a release too?

**Comment by JackSzwergold** [comment]
FWIW, if you want to get the new `import` functionality that exists in this GitHub repo’s `master` branch, just uninstall the version you initially installed via `pip3 install` like this:

```
pip3 uninstall semiphemeral
```

And now install this repo’s `master` branch version like this:

```
pip3 install git+ssh://git@github.com/micahflee/semiphemeral.git
```

Left [more details on how `import` works](https://github.com/micahflee/semiphemeral/issues/109#issuecomment-1321195790) in this other comment to a similar issue post.
