### ISSUE TITLE
FR: Render tweets locally

### ISSUE THREAD

**Issue by JohnVeness** [micahflee/semiphemeral#105]
For me, the current Tweets page on the --configure website takes at least a minute to display just one page of tweets, I think because it uses twitter.com to embed them. Would it be possible to instead display the tweets using data already in the database? Obviously this wouldn't include media, but for text-only tweets should be much quicker. Thanks!

**Comment by JackSzwergold** [comment]
Agreed with this request. Or perhaps display only the basic details: Tweet text and date and possibly tweet ID.
