### ISSUE TITLE
Semiphemeral frontend not working due to jQuery missing

### ISSUE THREAD

**Issue by rixx** [micahflee/semiphemeral#11]
None of the JavaScript features work for me, including the statistics sidebar and any/all tweet interactions. The browser console says:

```
The script from “http://127.0.0.1:8080/static/js/lib/jquery-3.4.1.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.
Loading failed for the <script> with source “http://127.0.0.1:8080/static/js/lib/jquery-3.4.1.min.js”.
ReferenceError: $ is not defined
ReferenceError: $ is not defined
```

I installed semipheremal via pip (in a virtualenv). Not sure at which point it failed to download the jquery bundle, but it did. Adding it manually works.

**Comment by micahflee** [comment]
This was fixed in this PR https://github.com/micahflee/semiphemeral/pull/6 and I pushed a new version (0.3) to PyPi earlier today. Updating to the latest version should fix it:

```
pip3 install --upgrade semiphemeral
```

**Comment by MatthewReinbold** [comment]
Can confirm that upgrading to 0.3 fixed this issue on my install
