### ISSUE TITLE
PSA: Twitter API access will not be free after 9 Feb

### ISSUE THREAD

**Issue by JohnVeness** [micahflee/semiphemeral#117]
https://twitter.com/TwitterDev/status/1621026986784337922

> Starting February 9, we will no longer support free access to the Twitter API, both v2 and v1.1. A paid basic tier will be available instead

That's that then.

**Comment by justingoldberg** [comment]
It's nice to see the woke @micahflee getting cancelled.

**Comment by justingoldberg** [comment]
Perhaps the next level is an electron browser directly scraping, posting, deleting, etc....

**Comment by SUPER7X** [comment]
> Note that free access is still available but severely limited. There are now 3 tiers: Free (aka Essential), Basic, Enterprise

Forgive me as someone super unfamiliar with the Twitter API, but what can be done with the Free tier, with 1500 posts per month? Can you still unlike tweets?
