### ISSUE TITLE
Twitter's new API is live - Semiphemeral no longer works

### ISSUE THREAD

**Issue by navjotjsingh** [micahflee/semiphemeral#123]
The app no longer seems to work with the free API given the restrictions I guess.

**Comment by bmacphail** [comment]
![image](https://user-images.githubusercontent.com/12399661/232662708-8cc0453b-402c-4dd7-b7bd-2ab2014be962.png) 

Had my API access revoked today...

**Comment by jon-chuang** [comment]
fuck twitter
