### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by matthiaslischka** [micahflee/semiphemeral#124]
Is the project dead?

[semiphemeral.com](https://semiphemeral.com/) is returning 500 Internal Server Error for quite some time now and the service seems down. No tweet about any issues though and no update on the current status.

Is this because of the new API? Is the project discontinued? An update would be nice.

BR Matthias

**Comment by Anzeigenhai** [comment]
Yep, the project is dead due to twitter new api business plan.
Tweetpy 4.0 no longer works totally
Tweetpy 3.0 returns API 1.1 issues (For 2.0 you have to pay)

Either way the semiphemeral returns error 500 if you want to fetch tweets.

**Comment by jkmaxwell** [comment]
@micahflee would you consider porting this for Bluesky? Many of us would like it there as well. I don't possess the eng knowledge to do this or I would contribute, myself.
