### ISSUE TITLE
https://semiphemeral.com/ stopped functioning 

### ISSUE THREAD

**Issue by MbNny** [micahflee/semiphemeral#126]
https://semiphemeral.com/ stopped functioning 

 happens when click Start Semiphemeral or Download my Twitter history again. The engine just did not start...

**Comment by ihamzapped** [comment]
The cli version is not working either. Gives the same internal server error as the hosted version
![brave_screenshot](https://github.com/micahflee/semiphemeral/assets/40671805/c7a57611-ed1a-45b3-b4ee-13273b2fc836)
