### ISSUE TITLE
"unretweet" doesn't effect unless "delete old tweets" is ticked

### ISSUE THREAD

**Issue by lourkeur** [micahflee/semiphemeral#16]
When I first run `semiphemeral delete`, my old likes were removed, but not my old retweets. I noticed that only my likes had been fetched, so there was no way for `delete` to delete anything. I had to both tick "delete old tweets" and reset `since_id` in the configuration file to have my retweets fetched. After doing that, I unticked "delete old tweets", and `delete` deleted my retweets as expected.

This is strictly a UX issue, the core functionality worked as expected.

**Comment by micahflee** [comment]
Ahh, so you "delete old tweets" was unchecked, but "unretweet tweets older than x days" was checked. It seems like the solution to this is if "unretweet tweets" it checked, `semiphemeral fetch` should download your entire timeline history, just like it does when "delete old tweets" is checked.

**Comment by lourkeur** [comment]
I think so, yes.
