### ISSUE TITLE
not enough info for creating the twitter app

### ISSUE THREAD

**Issue by claudioruiz** [micahflee/semiphemeral#2]
> You must supply Twitter API credentials here, which you can get by following this guide (basically, you need to login to https://developer.twitter.com/ and create a new "Twitter app" that only you will be using).

At the moment of creating a twitter app it's required to include a Website URL and a Callback URLs. I'm assuming the latter is something like 127.0.0.1:8080, but no clue about the Website URL, assuming this is meant to be used in a local machine.

**Comment by KonradIT** [comment]
You can use https://github.com/micahflee/semiphemeral.

**Comment by micahflee** [comment]
Yeah just using https://github.com/micahflee/semiphemeral is why I'm doing :) -- still, it might be good to explain this in the readme, so I'll leave this issue open until I can improve the documentation.
