### ISSUE TITLE
Semiphemeral fetch only getting about 3 months of tweets

### ISSUE THREAD

**Issue by KonradIT** [micahflee/semiphemeral#21]
Hi, I don't know if this is a Twitter limitation or something from tweepy, but running `fetch` after some time stops at 2019-03-27 for some reason, prints "Calculating which threads should be excluded" and then exits.

Version is 0.3

**Comment by russss** [comment]
This does apparently happen sometimes, especially if you've deleted chunks of tweets in the past. Twitter [mentions it here](https://help.twitter.com/en/using-twitter/missing-tweets).

I'm working on a feature to import tweets from a Twitter data export to circumvent this.

**Comment by KonradIT** [comment]
Neat, will wait for this.

**Comment by PeterDukeMedia** [comment]
This happens with me too. and then when I try to delete, I get:

Deleting 660 retweets, starting with the earliest
Error for tweet 1142912880230092800: Read-only application cannot POST.  
# *660

AND

Deleting 1444 tweets, starting with the earliest
Error for tweet 960218552593612800: Read-only application cannot POST.
# *1444

**Comment by KonradIT** [comment]
Something's wrong with your API application configuration
