### ISSUE TITLE
Feature request: keep selected tweets even if they are unliked

### ISSUE THREAD

**Issue by dysinger** [micahflee/semiphemeral#27]
First, let me thank you for this useful software. I am grateful.  I would like to ask for a small feature to be implemented in the future.

"As a KeyBase user, I would like to verify myself via a Twitter tweet. I want the tweet to stay forever, even if it isn't liked by anyone."

Possibly a place in the configuration UI for listing specific IDs not to be deleted even if they match criteria for deletion?

**Comment by KonradIT** [comment]
I also have had this problem in the past and even [submitted a PR that whitelists keybase proofs](https://github.com/micahflee/semiphemeral/pull/25).

**Comment by kees** [comment]
After loading your archive (see PR #23 ), use the "configure" mode, click "tweets", and you can pick the tweets you want to keep.
