### ISSUE TITLE
Support deleting old DMs

### ISSUE THREAD

**Issue by micahflee** [micahflee/semiphemeral#29]
The bug in tweepy that prevented DM support has been fixed (https://github.com/tweepy/tweepy/issues/1081) and tweepy 3.8.0 has been released, so now there's no excuse to not make semiphemeral automatically delete old DMs too.

**Comment by micahflee** [comment]
I'm getting close, but running into another tweepy issue. It looks like the new change that re-adds DM support didn't implement cursors properly (because twitter is implementing cursors differently in their new DM API), resulting in this bug: https://github.com/tweepy/tweepy/issues/1261 -- but there's already a PR to fix it: https://github.com/tweepy/tweepy/pull/1262

This issue is block until this is merged and there's a new version of tweepy released.

**Comment by ilf** [comment]
Tweepy [3.9.0 is now released](https://github.com/tweepy/tweepy/releases/tag/v3.9.0), including [DMCursorIterator](https://github.com/tweepy/tweepy/pull/1262). So this should be possible now?
