### ISSUE TITLE
i can't unretweet

### ISSUE THREAD

**Issue by pixelead0** [micahflee/semiphemeral#34]
How to delete the retweets from my timeline?

**Comment by dysinger** [comment]
I had this problem with one old retweet. I toggled the retweet icon a few times and it went away. This is because twitter doesn't ever actually delete anything I bet. It's just a flag.

**Comment by kees** [comment]
For very old stuff, you'll need to download your Twitter archive an import it, now that #23 is merged. Please reopen this if the problem persists. :)
