### ISSUE TITLE
command to add additional tweet IDs for consideration

### ISSUE THREAD

**Issue by samsmith** [micahflee/semiphemeral#39]
There is no way to add tweet IDs to delete into semiphemeral other than being IDs that come back from the twitter API (which only gives the last n tweets).

I have a decade of tweets, and deletion within the API-restrictions is going to take forever, but I can post-process the zip file twitter make available, but I can't then run those tweet IDs against t semiphemeral... I'd end up reimplementing semiphemeral in my analysis script.

Could a command be added to take  a list of tweet IDs/URLs on STDIN, and run them against the tests for deletion or not?

**Comment by kees** [comment]
I think the merge of PR #23 solves this in the sense that the archive can be used to direct which to delete. Please reopen if this isn't the case. :)
