### ISSUE TITLE
I selected unlike old tweets but I still have 47k likes

### ISSUE THREAD

**Issue by dysinger** [micahflee/semiphemeral#42]
I've been running semiphemeral for a long while now. I like it. Thank you.

I'm just curious about how I still have 47k likes. In fact, I can scroll through all my old likes from today until the beginning of time. It's not unliking them even though I have deleted old tweets and unlike tweets selected in the configuration panel.

![Screenshot from 2020-02-04 12-05-50](https://user-images.githubusercontent.com/447/73782324-c533a380-4746-11ea-98ff-b15cc20d9673.png)

![Screenshot from 2020-02-04 12-03-45](https://user-images.githubusercontent.com/447/73782168-7ab22700-4746-11ea-801b-cfe58d411e54.png)

**Comment by peteyreplies** [comment]
Did you download your twitter archive and reference `like.js` as prescribed by the docs?

**Comment by kees** [comment]
With #23 merged, I think this should be solved with an archive import now. Please reopen if not. :)
