### ISSUE TITLE
Unable to get 'unlike' function working

### ISSUE THREAD

**Issue by c-lang18** [micahflee/semiphemeral#45]
Been having some trouble running Semiphemeral to remove old likes, when running as per instructions [here](https://pypi.org/project/semiphemeral/) I just get 'invalid file' even though the instructions are followed to the letter, and the data was pulled from today. 

Unsure if this is related, but when following [these steps] (https://github.com/micahflee/semiphemeral/issues/31#issuecomment-515802699) I get an error:

>   File "C:\Users\Caro\.virtualenvs\semiphemeral-0gm4sUC6\lib\site-packages\sqlalchemy\util\compat.py", line 331, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

**Comment by kees** [comment]
Try again using "pipenv" as described in the README.md with the latest version of semiphemeral from github?
