### ISSUE TITLE
Error for tweet 1231878174461469696: Read-only application cannot POST.

### ISSUE THREAD

**Issue by kingarawana** [micahflee/semiphemeral#51]
**Error for tweet 1231878174461469696: Read-only application cannot POST.**

Anyone getting this error?

**Comment by kees** [comment]
In you Twitter Developer Dashboard for the project, switch your permissions away from Read-Only, and then regenerate your Access Token & Secret (and update Semiphemeral with the new ones).

**Comment by kees** [comment]
Closing for now.
