### ISSUE TITLE
Twitter Sign-In functionality on a self-hosted instance

### ISSUE THREAD

**Issue by notthebee** [micahflee/semiphemeral#60]
I noticed that the only way to use a self-hosted instance of Semiphemeral is to have a developer account associated with the Twitter account that you want to delete information from. 

In my case, however, my developer account application got rejected and currently there's no way to appeal the decision. Which means that if you get rejected once, you're left with no developer access forever, unless you create a new account.

It would be nice for the self-hosted version to have a possibility to sign in with a Twitter account that isn't associated with the API tokens, just like on https://semiphemeral.com/

**Comment by kees** [comment]
I appealed my rejection multiple times; just email them with more details. This project will continue to require a full API account, so I'm going to close this for now.
