### ISSUE TITLE
Retweet doesn’t count quote retweets

### ISSUE THREAD

**Issue by da2x** [micahflee/semiphemeral#62]
Hi, e.g. [this tweet](https://twitter.com/DaAleksandersen/status/1303304909618581504) is show in Semiphemeral as having 2 retweets. That number doesn’t count the 6 quote retweets, though. It probably should if the API provides that number?

**Comment by kees** [comment]
There doesn't appear to be a way to do this without some heavy searching via the Twitter API, unfortunately. Some details are here:
https://stackoverflow.com/questions/31373259/how-to-find-all-retweet-with-comments-for-a-particular-tweet-using-api
https://twittercommunity.com/t/how-to-fetch-retweets-and-quote-tweets-from-the-twitter-v2-search-api/156573
