### ISSUE TITLE
group-DMs seem to be ignored

### ISSUE THREAD

**Issue by kees** [micahflee/semiphemeral#66]
I have a few group DMs that even "delete_dms" seems to ignore when looking for old DMs to delete. I suspect fixing this means needing to parse some of the other DM data-dump files.

**Comment by vaurora** [comment]
Looks like API access to group DMs does not exist and is "not currently a priority." You can express your opinion by voting on this I guess:

https://twitterdevfeedback.uservoice.com/forums/921790-twitter-developer-labs/suggestions/37689256-allow-access-to-dm-group-conversations-via-twitter

(Hi, Kees!)
