### ISSUE TITLE
When Proxy is not defined the default is a "None" string that throws an exception

### ISSUE THREAD

**Issue by twaddington** [micahflee/semiphemeral#71]
This prevents semiphemeral from working at all and throws an exception.

To reproduce create a new install and run configure. Fill out the configuration but leave the default value for Proxy. Upon saving an exception will be thrown. Any attempt to run fetch at this point will throw a similar exception.

To fix the issue run configure again but delete the default "None" value for Proxy and save with a blank value.

**Comment by kees** [comment]
This should be fixed via PR #69 and PR #90 which corrects the default proxy string and handles the prior bad values.
