### ISSUE TITLE
Investigate whether the v2 unliking API works on old tweets

### ISSUE THREAD

**Issue by FiloSottile** [micahflee/semiphemeral#80]
There's a new v2 API for liking and unliking tweets. Maybe it doesn't have the limitations of the v1.1 one in relation to old likes, making the noisy and annoying `unlike` mode unnecessary.

https://developer.twitter.com/en/docs/twitter-api/tweets/likes/introduction
https://twittercommunity.com/t/announcing-new-manage-likes-endpoints-for-thetwitter-api-v2/152780

**Comment by cyphers** [comment]
I'm not sure the old like then unlike method is working anymore. Perhaps it is required to migrate to this new API and not just a convenience? For about a week or more, all I get running the unlike --filename ~/like.js command is this:

Error liking tweet 1234567890: [{'code': 139, 'message': 'You have already favorited this status.'}]

I'm getting the feeling this maybe a "required" API migration.

**Comment by FiloSottile** [comment]
Does unliking old tweets through the v1.1 API work now? Maybe they fixed the v1.1 API while developing the v2 one.
