### ISSUE TITLE
Delete DMs not working

### ISSUE THREAD

**Issue by ghost** [micahflee/semiphemeral#83]
I downloaded my data from twitter and did the following:

![image](https://user-images.githubusercontent.com/53082621/126883485-de7f4610-2c56-4283-afb2-65f6db01ff05.png)

As you can see in the image, I ran the command and get an error that should NOT happen.

**Comment by thejoker3000** [comment]
anything? anyone?

**Comment by thejoker3000** [comment]
found the issue see below.
-------

**ERROR 1**
https://imgur.com/a/bX9pJ1d

**ERROR 2**
➜  cp direct-messages.js direct-message.js
➜   semiphemeral delete_dms --filename direct-message.js                                  
semiphemeral 0.6
File expected to start with: `window.YTD.direct_message.part0 = `
➜  cat direct-message.js | more
window.YTD.direct_messages.part0 = [
  {
    "dmConversation" : {

**Comment by thejoker3000** [comment]
don't know how to fix and test but that's the error. Hopefully you see this and get to fix it because it's a pain in the ass to rename things instead of working on first run

**Comment by kees** [comment]
This should be fixed with PR #69 which fixes a typo in the expected file name.
