### ISSUE TITLE
Expired TLS Certificate on https://semiphemeral.com/

### ISSUE THREAD

**Issue by hexandcube** [micahflee/semiphemeral#86]
The TLS certificate for semiphemeral.com has expired on Mon, 01 Nov 2021 16:30:08 GMT.

![image](https://user-images.githubusercontent.com/41151156/139717602-871d4d6c-b95d-46f0-b591-d95729e2b84b.png)

**Comment by kees** [comment]
Those appears to have been solved. Current action expiration is June 2022.
