### ISSUE TITLE
Update API usage to Tweepy 4.x

### ISSUE THREAD

**Issue by kees** [micahflee/semiphemeral#92]
Newer Twitter API features should be available in Tweepy 4.x, which might solve some of the outstanding feature requests here. However, there were a lot of API-breaking changes in Tweepy 4.x vs 3.10, so some large changes may be needed in semiphemeral...

**Comment by Flash1232** [comment]
I think you should add a disclaimer for new potential app users as they cannot currently use it: https://github.com/micahflee/semiphemeral/issues/94#issuecomment-1001671885

**Comment by kees** [comment]
https://docs.tweepy.org/en/stable/faq.html#tweepy-v4

**Comment by ChawiBiker** [comment]
Is there a chance to get an update to this new Tweepy version?

**Comment by ekevoo** [comment]
Workaround is pinning Tweepy to an older version:

```
pip install semiphemeral 'tweepy<4.0'
```

I do not know whether changing `setup.py` similarly solves the problem.

**Comment by byteborg** [comment]
`pip install -U tweepy==3.10.0` when another version was installed previously.
